definition:
  kind: synchronous
  arguments:
  - name: workflow_id
    type: uuid!
  - name: customer_message
    type: String
  output:
    kind: object
    fields:
    - name: run_id
      type: uuid!
    - name: status
      type: String!
  handler:
    endpoint: {{env.API_URL}}/api/trigger-workflow-run
    method: POST
  headers:
  - name: Content-Type
    value: application/json
  - name: X-Hasura-User-Id
    value_from_session_variable: x-hasura-user-id
  - name: X-Hasura-Role
    value_from_session_variable: x-hasura-role
